### PR TITLE
Updates JS code to work with new UI

### PR DESCRIPTION
**Pull request by katstasaph**
At some point the TikTok UI was changed and this stopped working; I've updated it so it works again. It also includes share count if that is listed. (Also fixed typos and the like.)

~~Note: There are now two different ways you can view TikTok comments in a web browser. The old one appears when you click a video after a search and has everything in a pop-up. The new one appears when you directly navigate to a URL or reload the page, has the comments underneath the video, and has no pop-up. Needless to say all the XPaths are different, so this will only work on the older one. (The culprit is the video URL, creator name, etc., so it's probably possible to go back to class names for those.)~~

Now works on comment lists accessed via TikTok search as well as direct URLs.

Limitations: Google Chrome will run out of memory after a loading certain amount of comments; on my machine it's about 4,000. This seems to be an inherent limitation; I've tried various ways of batching but so far have not managed to make this consistently work on larger amounts of comments.

### CODE REVIEW

**Comment by prabeshAryal** [comment]
**There seems this issue, please solve ASAP!**

js_issue

_Tried removing problem causing lines, that doesn't seem to be issue as similar error was arising again for another line._

**Comment by BelTol3011** [comment]
Thanks for creating this fix!

**Comment by BelTol3011** [comment]
@katstasaph please release a fixed version. I get the same error as @prabesharyal.

**Comment by katstasaph** [comment]
Are you viewing this directly from a URL? In other words, are the comments on the bottom of the page, below the video, or in a pop-up window, next to the video?

**Comment by prabeshAryal** [comment]
I am viewing on the actual TikTok videopage. Comments are on bottom not on
sidebar. I did try both btw.

**Comment by katstasaph** [comment]
Sorry for the delay on this, life stuff. This should now work on both.

**Pull request merged**
